version: '3.8'

services:
  web:
    build: .
    container_name: sistema_escolar
    image: sistema_escolar:1.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
